# Generated by Django 4.2.2 on 2023-07-14 07:09

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_model",
            name="bdate",
            field=models.DateField(validators=[blog_app.models.validate_date_format]),
        ),
    ]
